from __future__ import annotations

import hashlib
import math
import re
from dataclasses import dataclass
from datetime import datetime, timedelta, timezone
from typing import Any

from app.embeddings.service import EmbeddingService
from app.memory.models import MemoryEntry
from app.memory.service import MemoryService


@dataclass(frozen=True)
class IngestionResult:
    inserted: bool
    reason: str
    memory: MemoryEntry | None
    debug: dict[str, Any]


class MemoryIngestionWorker:
    def __init__(self, memory_service: MemoryService, embeddings: EmbeddingService) -> None:
        self._memory = memory_service
        self._embeddings = embeddings

    def ingest(
        self,
        tenant_id: str,
        owner_agent_id: str,
        scope: str,
        raw_content: str,
        source_ref: str | None = None,
        group_id: str | None = None,
        metadata: dict[str, Any] | None = None,
    ) -> IngestionResult:
        cleaned = self._normalize_content(raw_content)
        if not cleaned:
            return IngestionResult(False, "empty_after_normalization", None, {"raw_length": len(raw_content)})

        content_hash = hashlib.sha256(cleaned.encode("utf-8")).hexdigest()
        existing = self._memory.list_by_tenant(tenant_id)
        if any(m.content_hash == content_hash for m in existing):
            return IngestionResult(False, "duplicate_content_hash", None, {"content_hash": content_hash})
        if source_ref and any(m.source_ref == source_ref for m in existing):
            return IngestionResult(False, "duplicate_source_ref", None, {"source_ref": source_ref})

        embedding = self._embeddings.embed(cleaned)
        embedding = self._normalize_vector(embedding)
        if not self._embeddings.validate(embedding):
            return IngestionResult(False, "embedding_dimension_mismatch", None, {"dim": len(embedding)})
        near_dup = self._near_duplicate(existing, embedding, threshold=0.985)
        if near_dup:
            return IngestionResult(False, "near_duplicate", near_dup, {"duplicate_id": near_dup.id})

        entry_type = self._classify(cleaned)
        extracted = self._extract(cleaned)
        importance, confidence = self._score(cleaned, entry_type, extracted)
        valid_from, valid_until = self._validity_window(entry_type, confidence)
        tags = self._tag(cleaned, metadata or {}, extracted)

        memory = self._memory.create(
            tenant_id=tenant_id,
            owner_agent_id=owner_agent_id,
            scope=scope,
            content=cleaned,
            group_id=group_id,
            entry_type=entry_type,
            tags=tags,
            source_ref=source_ref,
            embedding=embedding,
            content_hash=content_hash,
            importance=importance,
            confidence=confidence,
            valid_from=valid_from,
            valid_until=valid_until,
            metadata={
                "raw_type": (metadata or {}).get("type"),
                "facts": extracted["facts"],
                "outcomes": extracted["outcomes"],
                "preferences": extracted["preferences"],
                "constraints": extracted["constraints"],
            },
        )
        return IngestionResult(
            True,
            "inserted",
            memory,
            {
                "entry_type": entry_type,
                "importance": importance,
                "confidence": confidence,
                "tags": tags,
                "content_hash": content_hash,
            },
        )

    def _normalize_content(self, raw: str) -> str:
        cleaned = re.sub(r"\s+", " ", raw).strip()
        boilerplate = [
            "Sent from my iPhone",
            "This message may contain confidential information.",
            "Generated by automated system.",
        ]
        for phrase in boilerplate:
            cleaned = cleaned.replace(phrase, "").strip()
        return re.sub(r"\s+", " ", cleaned).strip()

    def _classify(self, content: str) -> str:
        lowered = content.lower()
        if any(word in lowered for word in ("always", "never", "must", "prefer", "policy")):
            return "fact"
        if any(word in lowered for word in ("completed", "done", "resolved", "failed", "outcome")):
            return "episode"
        return "message"

    def _extract(self, content: str) -> dict[str, list[str]]:
        lowered = content.lower()
        facts = [content] if any(k in lowered for k in ("is ", "are ", "must", "never")) else []
        outcomes = [content] if any(k in lowered for k in ("completed", "resolved", "failed", "shipped")) else []
        preferences = [content] if any(k in lowered for k in ("prefer", "like", "avoid")) else []
        constraints = [content] if any(k in lowered for k in ("must", "cannot", "never", "required")) else []
        return {
            "facts": facts,
            "outcomes": outcomes,
            "preferences": preferences,
            "constraints": constraints,
        }

    def _score(self, content: str, entry_type: str, extracted: dict[str, list[str]]) -> tuple[int, float]:
        importance = 30 + min(40, len(content) // 8)
        if entry_type == "fact":
            importance += 20
        elif entry_type == "episode":
            importance += 10
        if extracted["constraints"]:
            importance += 10
        importance = max(0, min(100, importance))

        confidence = 0.4 + (0.2 if entry_type == "fact" else 0.1 if entry_type == "episode" else 0.0)
        if extracted["facts"]:
            confidence += 0.1
        confidence = max(0.0, min(1.0, confidence))
        return importance, confidence

    def _validity_window(self, entry_type: str, confidence: float) -> tuple[datetime, datetime | None]:
        now = datetime.now(tz=timezone.utc)
        if entry_type == "message":
            return now, now + timedelta(days=30)
        if confidence < 0.6:
            return now, now + timedelta(days=90)
        return now, None

    def _tag(self, content: str, metadata: dict[str, Any], extracted: dict[str, list[str]]) -> list[str]:
        tags: set[str] = set()
        for key in ("project", "user", "domain", "task_type"):
            value = metadata.get(key)
            if isinstance(value, str) and value:
                tags.add(f"{key}:{value}")
        if extracted["preferences"]:
            tags.add("category:preference")
        if extracted["constraints"]:
            tags.add("category:constraint")
        if "bug" in content.lower():
            tags.add("domain:engineering")
        return sorted(tags)

    def _near_duplicate(self, existing: list[MemoryEntry], candidate: list[float], threshold: float) -> MemoryEntry | None:
        for entry in existing:
            if not entry.embedding:
                continue
            sim = self._cosine_similarity(entry.embedding, candidate)
            if sim >= threshold:
                return entry
        return None

    def _normalize_vector(self, vector: list[float]) -> list[float]:
        norm = math.sqrt(sum(v * v for v in vector))
        if norm == 0:
            return vector
        return [v / norm for v in vector]

    def _cosine_similarity(self, a: list[float], b: list[float]) -> float:
        if len(a) != len(b):
            return -1.0
        dot = sum(x * y for x, y in zip(a, b))
        norm_a = math.sqrt(sum(x * x for x in a))
        norm_b = math.sqrt(sum(y * y for y in b))
        if norm_a == 0 or norm_b == 0:
            return -1.0
        return dot / (norm_a * norm_b)
